# ─────────────────────────────────────────────────────────────────────────────
# Project: local-first-voice-chatbot
# What you get:
# - docker-compose.yml (FastAPI gateway + Piper TTS)
# - server/app (FastAPI: STT via faster-whisper, LLM via llama.cpp or OpenAI, TTS proxy)
# - web/ (Minimal HTML/JS client with push-to-talk, WAV encoder)
# - scripts/ (helpers to fetch models)
# - .env.example (toggle local vs cloud)
# ─────────────────────────────────────────────────────────────────────────────

# =========================
# docker-compose.yml
# =========================
version: "3.9"
services:
  api:
    build: ./server
    container_name: voicebot_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/models
      - ./data:/data
      - ./server:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]


